version: '3.8'

services:
  asmr-reader:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: asmr-reader

    # Health check
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
