version: '3.8'

services:
  asmr-reader:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always # Improved restart policy
    container_name: asmr-reader

    # Resource constraints for optimization
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

    # Health check
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
